[tox]
skipsdist = True

[testenv]
allowlist_externals =
    rm
    uv
deps =
    cruft
commands =
    - rm -rf {toxinidir}/cookiecutter-pypackage
    - cruft create . --config-file test_config.yaml --no-input
    - uv --directory {toxinidir}/cookiecutter-pypackage sync
