[tox]
envlist =
    lint
    {py311,py312,py313,py314}-test
    combine-test-reports
isolated_build = True

[gh-actions]
python =
    3.11: py311-test
    3.12: py312-test
    3.13: py313-test
    3.14: py314-test

[testenv]
# Passes host environment variables to the tox environment.
passenv =
    CI
    PROJECT
    MATURITY
    SCOPE
    LOCATION
    UV_INDEX
    JFROG_CLI_*
    CODEMETER_HOST
    SOURCE_DATE_EPOCH
    JENKINS_URL
    TAG_NAME
    BUILD_NUMBER
    BRANCH_NAME
    CHANGE_TARGET
    VPU_*
# Define additional environment variables for all test environments.
setenv =
    VPU_DOCKER_IMAGE_NAME = {env:PACKAGE_NAME}
    VPU_DOCKER_REPOSITORIES = {env:PROJECT}-docker-{env:SCOPE}-{env:MATURITY}-{env:LOCATION}-local
# Allow those external commands in all test environments
allowlist_externals =
    jf

package = wheel  # Tell tox to build and install wheels instead of source distributions
wheel_build_env = .pkg  #  Share the same build environment – and thus wheel – across all tox environments.


[testenv:lint]
description = Run static checkers.
basepython = py311
setenv =
    {[testenv]setenv}
    DOCSDIR = {toxinidir}/docs
dependency_groups = lint
commands =
    # Check for common spelling mistakes
    codespell --builtin clear,en-GB_to_en-US
    # Check type hinting
    mypy .
    # Check formatting
    ruff format --check .
    # Lint source code
    ruff check .


[testenv:{py311,py312,py313,py314}-test]
description = Run doc tests and unit tests.
package = wheel
dependency_groups = test
setenv =
    {[testenv]setenv}
    PY_IGNORE_IMPORTMISMATCH=1
    COVERAGE_FILE = reports{/}.coverage.{envname}
commands =
    # Run tests and doctests from .py files
    pytest --junitxml=reports/pytest.xml.{envname} {posargs} src/ tests/


[testenv:combine-test-reports]
description = Combine test and coverage data from multiple test runs.
skip_install = true
setenv =
    {[testenv]setenv}
    COVERAGE_FILE = reports/.coverage
depends = {py311,py312,py313,py314}-test
deps =
    junitparser
    coverage[toml]
commands =
    junitparser merge --glob reports/pytest.xml.* reports/pytest.xml
    coverage combine --keep
    coverage html
    coverage xml


[testenv:docs]
description = Test and build the docs.
setenv =
    {[testenv]setenv}
    DOCSDIR = {toxinidir}/docs
    BUILDDIR = {toxinidir}/docs/build
dependency_groups = doc
commands =
    # Remove build directory
    python -c 'import shutil; shutil.rmtree("{env:BUILDDIR}", ignore_errors=True);'
    # Delete all files generated by sphinx-apidoc
    python -c 'import glob, os; [os.remove(f) for f in glob.glob("docs/cookiecutter_pypackage*")];'
    # Create dummy files to prevent warnings
    python -c 'import pathlib; pathlib.Path("{env:DOCSDIR}").joinpath("cookiecutter_pypackage.rst").write_text("");'
    python -c 'import pathlib; pathlib.Path("{env:DOCSDIR}").joinpath("license_compliance.rst").write_text("");'
    # Check *.md and *.rst files
    doc8 {env:DOCSDIR}
    pymarkdown scan -r {env:DOCSDIR}
    # Run doctests (only from .rst files in docs folder, doctests in .py files are covered by pytest)
    sphinx-build -b doctest -W -d "{env:BUILDDIR}/doctrees" "{env:DOCSDIR}" "{env:BUILDDIR}/doctest" {posargs}
    # Autogenerate docs from code
    sphinx-apidoc -f --no-toc -M -o docs/ src/cookiecutter_pypackage/ src/cookiecutter_pypackage/*/* src/cookiecutter_pypackage/*[!__init__].py
    # Dump OSS license information into the docs directory
    python {env:DOCSDIR}/_scripts/generate_license_information.py
    # Build the docs
    sphinx-build -b html -W -d "{env:BUILDDIR}/doctrees" "{env:DOCSDIR}" "{env:BUILDDIR}/html" {posargs}


[testenv:build]
description = Build the package.
dependency_groups =
    build
setenv =
    {[testenv]setenv}
commands =
    # Clean up build directories
    python -c 'from shutil import rmtree; rmtree("build", True); rmtree("dist", True)'
    # Build the package
    python -m build .

[testenv:build-docker]
description = Build the Docker image.
dependency_groups = ci
setenv =
    {[testenv]setenv}
commands =
    vpu docker build -f Dockerfile.prod


[testenv:publish]
description = Upload the package and the docker image(s)
dependency_groups = ci
setenv =
    {[testenv]setenv}
commands =
    vpu docker push
    jf twine --module='cookiecutter-pypackage' upload dist/*
