name: CI pipeline

permissions:
  contents: write
  id-token: write
  issues: write
  pages: write

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
    setup:
      uses: ./.github/workflows/setup.yml
      with:
        package_name: 'cookiecutter-pypackage'
        project: 'bypass'
        scope: 'private'
        maturity: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && 'production' || 'testing' }}
        location: 'cloud'
        registry: 'voraus.jfrog.io'

    build:
      needs:
        - setup
      uses: ./.github/workflows/build.yml
      secrets: inherit
      with:
        vpu_docker_registry: ${{ needs.setup.outputs.vpu_docker_registry }}
        vpu_docker_image_name: ${{ needs.setup.outputs.vpu_docker_image_name }}
        vpu_docker_repositories: ${{ needs.setup.outputs.vpu_docker_repositories }}
        build_name: ${{ needs.setup.outputs.build_name }}
        build_number: ${{ needs.setup.outputs.build_number }}

    tests-and-coverage:
      uses: ./.github/workflows/tests_and_coverage.yml
      needs:
        - build
      secrets: inherit

    lint:
      uses: ./.github/workflows/lint.yml
      needs:
        - setup
      secrets: inherit

    publish:
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      needs:
      - setup
      - build
      - tests-and-coverage
      - lint
      uses: ./.github/workflows/publish.yml
      secrets: inherit
      with:
        vpu_docker_registry: ${{ needs.setup.outputs.vpu_docker_registry }}
        vpu_docker_image_name: ${{ needs.setup.outputs.vpu_docker_image_name }}
        vpu_docker_repositories: ${{ needs.setup.outputs.vpu_docker_repositories }}
        pypi_deploy_repo: ${{ needs.setup.outputs.pypi_deploy_repo }}
        build_name: ${{ needs.setup.outputs.build_name }}
        build_number: ${{ needs.setup.outputs.build_number }}
